# Generated by Django 6.0.2 on 2026-02-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='outcome',
            field=models.CharField(choices=[('not_answered', 'Not Answered'), ('call_back_later', 'Call Back Later'), ('converted', 'Converted'), ('no_interest', 'No Interest'), ('not_called', 'Not Called')], default='not_called'),
        ),
        migrations.AddField(
            model_name='lead',
            name='type',
            field=models.CharField(choices=[('lead', 'Lead'), ('client', 'Client'), ('lost', 'Lost')], default='lead'),
        ),
    ]
